fixed detection of google-test

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1768,6 +1768,53 @@ fi
 
 } # ac_fn_c_try_link
 
+# ac_fn_cxx_try_link LINENO
+# -------------------------
+# Try to link conftest.$ac_ext, and return whether this succeeded.
+ac_fn_cxx_try_link ()
+{
+  as_lineno=${as_lineno-"$1"} as_lineno_stack=as_lineno_stack=$as_lineno_stack
+  rm -f conftest.$ac_objext conftest.beam conftest$ac_exeext
+  if { { ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval ac_try_echo="\"\$as_me:${as_lineno-$LINENO}: $ac_try_echo\""
+printf "%s\n" "$ac_try_echo"; } >&5
+  (eval "$ac_link") 2>conftest.err
+  ac_status=$?
+  if test -s conftest.err; then
+    grep -v '^ *+' conftest.err >conftest.er1
+    cat conftest.er1 >&5
+    mv -f conftest.er1 conftest.err
+  fi
+  printf "%s\n" "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+  test $ac_status = 0; } && {
+	 test -z "$ac_cxx_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext && {
+	 test "$cross_compiling" = yes ||
+	 test -x conftest$ac_exeext
+       }
+then :
+  ac_retval=0
+else $as_nop
+  printf "%s\n" "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_retval=1
+fi
+  # Delete the IPA/IPO (Inter Procedural Analysis/Optimization) information
+  # created by the PGI compiler (conftest_ipa8_conftest.oo), as it would
+  # interfere with the next link command; also delete a directory that is
+  # left behind by Apple's compiler.  We do this before executing the actions.
+  rm -rf conftest.dSYM conftest_ipa8_conftest.oo
+  eval $as_lineno_stack; ${as_lineno_stack:+:} unset as_lineno
+  as_fn_set_status $ac_retval
+
+} # ac_fn_cxx_try_link
+
 # ac_fn_cxx_try_run LINENO
 # ------------------------
 # Try to run conftest.$ac_ext, and return whether this succeeded. Assumes that
@@ -2227,53 +2274,6 @@ printf "%s\n" "$ac_res" >&6; }
 
 } # ac_fn_cxx_check_type
 
-# ac_fn_cxx_try_link LINENO
-# -------------------------
-# Try to link conftest.$ac_ext, and return whether this succeeded.
-ac_fn_cxx_try_link ()
-{
-  as_lineno=${as_lineno-"$1"} as_lineno_stack=as_lineno_stack=$as_lineno_stack
-  rm -f conftest.$ac_objext conftest.beam conftest$ac_exeext
-  if { { ac_try="$ac_link"
-case "(($ac_try" in
-  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
-  *) ac_try_echo=$ac_try;;
-esac
-eval ac_try_echo="\"\$as_me:${as_lineno-$LINENO}: $ac_try_echo\""
-printf "%s\n" "$ac_try_echo"; } >&5
-  (eval "$ac_link") 2>conftest.err
-  ac_status=$?
-  if test -s conftest.err; then
-    grep -v '^ *+' conftest.err >conftest.er1
-    cat conftest.er1 >&5
-    mv -f conftest.er1 conftest.err
-  fi
-  printf "%s\n" "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
-  test $ac_status = 0; } && {
-	 test -z "$ac_cxx_werror_flag" ||
-	 test ! -s conftest.err
-       } && test -s conftest$ac_exeext && {
-	 test "$cross_compiling" = yes ||
-	 test -x conftest$ac_exeext
-       }
-then :
-  ac_retval=0
-else $as_nop
-  printf "%s\n" "$as_me: failed program was:" >&5
-sed 's/^/| /' conftest.$ac_ext >&5
-
-	ac_retval=1
-fi
-  # Delete the IPA/IPO (Inter Procedural Analysis/Optimization) information
-  # created by the PGI compiler (conftest_ipa8_conftest.oo), as it would
-  # interfere with the next link command; also delete a directory that is
-  # left behind by Apple's compiler.  We do this before executing the actions.
-  rm -rf conftest.dSYM conftest_ipa8_conftest.oo
-  eval $as_lineno_stack; ${as_lineno_stack:+:} unset as_lineno
-  as_fn_set_status $ac_retval
-
-} # ac_fn_cxx_try_link
-
 # ac_fn_cxx_try_cpp LINENO
 # ------------------------
 # Try to preprocess conftest.$ac_ext, and return whether this succeeded.
@@ -2331,7 +2331,7 @@ else $as_nop
 #define $2 innocuous_$2
 
 /* System header to define __stub macros and hopefully few prototypes,
-   which can conflict with char $2 (); below.  */
+   which can conflict with char $2 (void); below.  */
 
 #include <limits.h>
 #undef $2
@@ -2342,7 +2342,7 @@ else $as_nop
 #ifdef __cplusplus
 extern "C"
 #endif
-char $2 ();
+char $2 (void);
 /* The GNU C library defines this for functions which it implements
     to always fail with ENOSYS.  Some functions are actually named
     something starting with __ and the normal name is an alias.  */
@@ -2768,9 +2768,7 @@ struct stat;
 /* Most of the following tests are stolen from RCS 5.7 src/conf.sh.  */
 struct buf { int x; };
 struct buf * (*rcsopen) (struct buf *, struct stat *, int);
-static char *e (p, i)
-     char **p;
-     int i;
+static char *e (char **p, int i)
 {
   return p[i];
 }
@@ -2821,6 +2819,7 @@ extern int puts (const char *);
 extern int printf (const char *, ...);
 extern int dprintf (int, const char *, ...);
 extern void *malloc (size_t);
+extern void free (void *);
 
 // Check varargs macros.  These examples are taken from C99 6.10.3.5.
 // dprintf is used instead of fprintf to avoid needing to declare
@@ -6452,11 +6451,11 @@ if test x$ac_prog_cxx_stdcxx = xno
 then :
   { printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking for $CXX option to enable C++11 features" >&5
 printf %s "checking for $CXX option to enable C++11 features... " >&6; }
-if test ${ac_cv_prog_cxx_cxx11+y}
+if test ${ac_cv_prog_cxx_11+y}
 then :
   printf %s "(cached) " >&6
 else $as_nop
-  ac_cv_prog_cxx_cxx11=no
+  ac_cv_prog_cxx_11=no
 ac_save_CXX=$CXX
 cat confdefs.h - <<_ACEOF >conftest.$ac_ext
 /* end confdefs.h.  */
@@ -6498,11 +6497,11 @@ if test x$ac_prog_cxx_stdcxx = xno
 then :
   { printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking for $CXX option to enable C++98 features" >&5
 printf %s "checking for $CXX option to enable C++98 features... " >&6; }
-if test ${ac_cv_prog_cxx_cxx98+y}
+if test ${ac_cv_prog_cxx_98+y}
 then :
   printf %s "(cached) " >&6
 else $as_nop
-  ac_cv_prog_cxx_cxx98=no
+  ac_cv_prog_cxx_98=no
 ac_save_CXX=$CXX
 cat confdefs.h - <<_ACEOF >conftest.$ac_ext
 /* end confdefs.h.  */
@@ -8461,8 +8460,14 @@ printf %s "checking for pthread_join in LIBS=$PTHREAD_LIBS with CFLAGS=$PTHREAD_
 
 /* Override any GCC internal prototype to avoid an error.
    Use char because int might match the return type of a GCC
-   builtin and then its argument prototype would still apply.  */
-char pthread_join ();
+   builtin and then its argument prototype would still apply.
+   The 'extern "C"' is for builds by C++ compilers;
+   although this is not generally supported in C code supporting it here
+   has little cost and some practical benefit (sr 110532).  */
+#ifdef __cplusplus
+extern "C"
+#endif
+char pthread_join (void);
 int
 main (void)
 {
@@ -9046,22 +9051,23 @@ unsigned short int ascii_mm[] =
 		int use_ebcdic (int i) {
 		  return ebcdic_mm[i] + ebcdic_ii[i];
 		}
-		extern int foo;
-
-int
-main (void)
-{
-return use_ascii (foo) == use_ebcdic (foo);
-  ;
-  return 0;
-}
+		int
+		main (int argc, char **argv)
+		{
+		  /* Intimidate the compiler so that it does not
+		     optimize the arrays away.  */
+		  char *p = argv[0];
+		  ascii_mm[1] = *p++; ebcdic_mm[1] = *p++;
+		  ascii_ii[1] = *p++; ebcdic_ii[1] = *p++;
+		  return use_ascii (argc) == use_ebcdic (*p);
+		}
 _ACEOF
-if ac_fn_cxx_try_compile "$LINENO"
+if ac_fn_cxx_try_link "$LINENO"
 then :
-  if grep BIGenDianSyS conftest.$ac_objext >/dev/null; then
+  if grep BIGenDianSyS conftest$ac_exeext >/dev/null; then
 	      ac_cv_c_bigendian=yes
 	    fi
-	    if grep LiTTleEnDian conftest.$ac_objext >/dev/null ; then
+	    if grep LiTTleEnDian conftest$ac_exeext >/dev/null ; then
 	      if test "$ac_cv_c_bigendian" = unknown; then
 		ac_cv_c_bigendian=no
 	      else
@@ -9070,7 +9076,8 @@ then :
 	      fi
 	    fi
 fi
-rm -f core conftest.err conftest.$ac_objext conftest.beam conftest.$ac_ext
+rm -f core conftest.err conftest.$ac_objext conftest.beam \
+    conftest$ac_exeext conftest.$ac_ext
 else $as_nop
   cat confdefs.h - <<_ACEOF >conftest.$ac_ext
 /* end confdefs.h.  */
@@ -11652,21 +11659,26 @@ fi
 
 report_have_gtest="no"
 
-{ printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking if googletest should be used for unittesting" >&5
-printf %s "checking if googletest should be used for unittesting... " >&6; }
+{ printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking if googletest 111 should be used for unittesting" >&5
+printf %s "checking if googletest 111 should be used for unittesting... " >&6; }
 
 # Check whether --enable-gtest was given.
 if test ${enable_gtest+y}
 then :
   enableval=$enable_gtest;
 else $as_nop
-  enable_gtest=
+  enable_gtest="yes"
 fi
 
 
 HAVE_GTEST="no"
+
 if test "$enable_gtest" != "no"
 then
+	if test "$enable_gtest" = "yes"
+	then
+		enable_gtest="wmlib/tests/googletest-release-1.10.0"
+	fi
 
 	if test -d "$enable_gtest"
 	then
@@ -11685,34 +11697,19 @@ then
 			GTEST_PREFIX="$enable_gtest/googletest"
 
 		fi
-		if test -f "$enable_gtest/include/gtest/gtest.h"
-		then
-			HAVE_GTEST="yes"
-			GTEST_PREFIX="$enable_gtest"
-
-		fi
-	fi
-	if test "$HAVE_GTEST" = "no"
-	then
-		if test -f "/usr/include/gtest/gtest.h"
-		then
-			HAVE_GTEST="yes"
-			GTEST_PREFIX="/usr"
-
-		fi
 	fi
 	if test "$HAVE_GTEST" = "yes"
 	then
-		{ printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: yesi" >&5
-printf "%s\n" "yesi" >&6; }
+		{ printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: yes" >&5
+printf "%s\n" "yes" >&6; }
 
 	else
-		{ printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: no" >&5
-printf "%s\n" "no" >&6; }
+		{ printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: no: not found" >&5
+printf "%s\n" "no: not found" >&6; }
 	fi
 else
-	{ printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: no" >&5
-printf "%s\n" "no" >&6; }
+	{ printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: no: disabled by user" >&5
+printf "%s\n" "no: disabled by user" >&6; }
 fi
 
 if test $HAVE_GTEST = "yes"
@@ -11817,60 +11814,6 @@ then :
 
 fi
 
-ac_fn_cxx_check_header_compile "$LINENO" "sys/socket.h" "ac_cv_header_sys_socket_h" "$ac_includes_default"
-if test "x$ac_cv_header_sys_socket_h" = xyes
-then :
-  printf "%s\n" "#define HAVE_SYS_SOCKET_H 1" >>confdefs.h
-
-fi
-
-ac_fn_cxx_check_header_compile "$LINENO" "sys/poll.h" "ac_cv_header_sys_poll_h" "$ac_includes_default"
-if test "x$ac_cv_header_sys_poll_h" = xyes
-then :
-  printf "%s\n" "#define HAVE_SYS_POLL_H 1" >>confdefs.h
-
-fi
-
-ac_fn_cxx_check_header_compile "$LINENO" "netinet/in.h" "ac_cv_header_netinet_in_h" "$ac_includes_default"
-if test "x$ac_cv_header_netinet_in_h" = xyes
-then :
-  printf "%s\n" "#define HAVE_NETINET_IN_H 1" >>confdefs.h
-
-fi
-
-ac_fn_cxx_check_header_compile "$LINENO" "arpa/nameser.h" "ac_cv_header_arpa_nameser_h" "$ac_includes_default"
-if test "x$ac_cv_header_arpa_nameser_h" = xyes
-then :
-  printf "%s\n" "#define HAVE_ARPA_NAMESER_H 1" >>confdefs.h
-
-fi
-
-ac_fn_cxx_check_header_compile "$LINENO" "resolv.h" "ac_cv_header_resolv_h" "
-	#include <sys/types.h>
-	#include <netinet/in.h>
-	#include <arpa/nameser.h>
-
-"
-if test "x$ac_cv_header_resolv_h" = xyes
-then :
-  printf "%s\n" "#define HAVE_RESOLV_H 1" >>confdefs.h
-
-fi
-
-ac_fn_cxx_check_header_compile "$LINENO" "netdb.h" "ac_cv_header_netdb_h" "$ac_includes_default"
-if test "x$ac_cv_header_netdb_h" = xyes
-then :
-  printf "%s\n" "#define HAVE_NETDB_H 1" >>confdefs.h
-
-fi
-
-ac_fn_cxx_check_header_compile "$LINENO" "arpa/inet.h" "ac_cv_header_arpa_inet_h" "$ac_includes_default"
-if test "x$ac_cv_header_arpa_inet_h" = xyes
-then :
-  printf "%s\n" "#define HAVE_ARPA_INET_H 1" >>confdefs.h
-
-fi
-
 ac_fn_cxx_check_header_compile "$LINENO" "strings.h" "ac_cv_header_strings_h" "$ac_includes_default"
 if test "x$ac_cv_header_strings_h" = xyes
 then :
@@ -11969,13 +11912,6 @@ then :
 
 fi
 
-ac_fn_cxx_check_header_compile "$LINENO" "valgrind/helgrind.h" "ac_cv_header_valgrind_helgrind_h" "$ac_includes_default"
-if test "x$ac_cv_header_valgrind_helgrind_h" = xyes
-then :
-  printf "%s\n" "#define HAVE_VALGRIND_HELGRIND_H 1" >>confdefs.h
-
-fi
-
 
 ac_func=
 for ac_item in $ac_func_cxx_list
@@ -12037,7 +11973,7 @@ static const char *tz_strings[] = {
 /* Return 0 if mktime fails to convert a date in the spring-forward gap.
    Based on a problem report from Andreas Jaeger.  */
 static int
-spring_forward_gap ()
+spring_forward_gap (void)
 {
   /* glibc (up to about 1998-10-07) failed this test. */
   struct tm tm;
@@ -12074,7 +12010,7 @@ mktime_test (time_t now)
 }
 
 static int
-irix_6_4_bug ()
+irix_6_4_bug (void)
 {
   /* Based on code from Ariel Faigon.  */
   struct tm tm;
@@ -12116,7 +12052,7 @@ bigtime_test (int j)
 }
 
 static int
-year_2050_test ()
+year_2050_test (void)
 {
   /* The correct answer for 2050-02-01 00:00:00 in Pacific time,
      ignoring leap seconds.  */
@@ -12415,7 +12351,7 @@ static const char *tz_strings[] = {
 /* Return 0 if mktime fails to convert a date in the spring-forward gap.
    Based on a problem report from Andreas Jaeger.  */
 static int
-spring_forward_gap ()
+spring_forward_gap (void)
 {
   /* glibc (up to about 1998-10-07) failed this test. */
   struct tm tm;
@@ -12452,7 +12388,7 @@ mktime_test (time_t now)
 }
 
 static int
-irix_6_4_bug ()
+irix_6_4_bug (void)
 {
   /* Based on code from Ariel Faigon.  */
   struct tm tm;
@@ -12494,7 +12430,7 @@ bigtime_test (int j)
 }
 
 static int
-year_2050_test ()
+year_2050_test (void)
 {
   /* The correct answer for 2050-02-01 00:00:00 in Pacific time,
      ignoring leap seconds.  */
@@ -12874,12 +12810,6 @@ then :
   printf "%s\n" "#define HAVE_GETTIMEOFDAY 1" >>confdefs.h
 
 fi
-ac_fn_cxx_check_func "$LINENO" "inet_ntoa" "ac_cv_func_inet_ntoa"
-if test "x$ac_cv_func_inet_ntoa" = xyes
-then :
-  printf "%s\n" "#define HAVE_INET_NTOA 1" >>confdefs.h
-
-fi
 ac_fn_cxx_check_func "$LINENO" "memmove" "ac_cv_func_memmove"
 if test "x$ac_cv_func_memmove" = xyes
 then :
@@ -12896,12 +12826,6 @@ ac_fn_cxx_check_func "$LINENO" "mkdir" "ac_cv_func_mkdir"
 if test "x$ac_cv_func_mkdir" = xyes
 then :
   printf "%s\n" "#define HAVE_MKDIR 1" >>confdefs.h
-
-fi
-ac_fn_cxx_check_func "$LINENO" "socket" "ac_cv_func_socket"
-if test "x$ac_cv_func_socket" = xyes
-then :
-  printf "%s\n" "#define HAVE_SOCKET 1" >>confdefs.h
 
 fi
 ac_fn_cxx_check_func "$LINENO" "__mingw_vasprintf" "ac_cv_func___mingw_vasprintf"
@@ -12923,30 +12847,6 @@ then :
 
 fi
 
-ac_fn_cxx_check_func "$LINENO" "gethostname" "ac_cv_func_gethostname"
-if test "x$ac_cv_func_gethostname" = xyes
-then :
-  printf "%s\n" "#define HAVE_GETHOSTNAME 1" >>confdefs.h
-
-fi
-ac_fn_cxx_check_func "$LINENO" "sethostname" "ac_cv_func_sethostname"
-if test "x$ac_cv_func_sethostname" = xyes
-then :
-  printf "%s\n" "#define HAVE_SETHOSTNAME 1" >>confdefs.h
-
-fi
-ac_fn_cxx_check_func "$LINENO" "getdomainname" "ac_cv_func_getdomainname"
-if test "x$ac_cv_func_getdomainname" = xyes
-then :
-  printf "%s\n" "#define HAVE_GETDOMAINNAME 1" >>confdefs.h
-
-fi
-ac_fn_cxx_check_func "$LINENO" "setdomainname" "ac_cv_func_setdomainname"
-if test "x$ac_cv_func_setdomainname" = xyes
-then :
-  printf "%s\n" "#define HAVE_SETDOMAINNAME 1" >>confdefs.h
-
-fi
 ac_fn_cxx_check_func "$LINENO" "uname" "ac_cv_func_uname"
 if test "x$ac_cv_func_uname" = xyes
 then :
@@ -13573,55 +13473,6 @@ then :
 
 fi
 
-ac_fn_cxx_check_func "$LINENO" "inet_ntop" "ac_cv_func_inet_ntop"
-if test "x$ac_cv_func_inet_ntop" = xyes
-then :
-  printf "%s\n" "#define HAVE_INET_NTOP 1" >>confdefs.h
-
-fi
-ac_fn_cxx_check_func "$LINENO" "inet_pton" "ac_cv_func_inet_pton"
-if test "x$ac_cv_func_inet_pton" = xyes
-then :
-  printf "%s\n" "#define HAVE_INET_PTON 1" >>confdefs.h
-
-fi
-ac_fn_cxx_check_func "$LINENO" "inet_aton" "ac_cv_func_inet_aton"
-if test "x$ac_cv_func_inet_aton" = xyes
-then :
-  printf "%s\n" "#define HAVE_INET_ATON 1" >>confdefs.h
-
-fi
-ac_fn_cxx_check_func "$LINENO" "inet_ntoa" "ac_cv_func_inet_ntoa"
-if test "x$ac_cv_func_inet_ntoa" = xyes
-then :
-  printf "%s\n" "#define HAVE_INET_NTOA 1" >>confdefs.h
-
-fi
-ac_fn_cxx_check_func "$LINENO" "inet_ntoa_r" "ac_cv_func_inet_ntoa_r"
-if test "x$ac_cv_func_inet_ntoa_r" = xyes
-then :
-  printf "%s\n" "#define HAVE_INET_NTOA_R 1" >>confdefs.h
-
-fi
-ac_fn_cxx_check_func "$LINENO" "inet_addr" "ac_cv_func_inet_addr"
-if test "x$ac_cv_func_inet_addr" = xyes
-then :
-  printf "%s\n" "#define HAVE_INET_ADDR 1" >>confdefs.h
-
-fi
-ac_fn_cxx_check_func "$LINENO" "inet_network" "ac_cv_func_inet_network"
-if test "x$ac_cv_func_inet_network" = xyes
-then :
-  printf "%s\n" "#define HAVE_INET_NETWORK 1" >>confdefs.h
-
-fi
-ac_fn_cxx_check_func "$LINENO" "inet_makeaddr" "ac_cv_func_inet_makeaddr"
-if test "x$ac_cv_func_inet_makeaddr" = xyes
-then :
-  printf "%s\n" "#define HAVE_INET_MAKEADDR 1" >>confdefs.h
-
-fi
-
 
 { printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking for pthread_set_name_np in -lpthread" >&5
 printf %s "checking for pthread_set_name_np in -lpthread... " >&6; }
@@ -13719,38 +13570,6 @@ fi
 
 
 
-{ printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking for sa_len in struct sockaddr" >&5
-printf %s "checking for sa_len in struct sockaddr... " >&6; }
-if test ${ac_cv_struct_sa_len+y}
-then :
-  printf %s "(cached) " >&6
-else $as_nop
-  cat confdefs.h - <<_ACEOF >conftest.$ac_ext
-/* end confdefs.h.  */
-#include <sys/types.h>
-#include <sys/socket.h>
-int
-main (void)
-{
-struct sockaddr s; s.sa_len;
-  ;
-  return 0;
-}
-_ACEOF
-if ac_fn_cxx_try_compile "$LINENO"
-then :
-  ac_cv_struct_sa_len=yes
-else $as_nop
-  ac_cv_struct_sa_len=no
-fi
-rm -f core conftest.err conftest.$ac_objext conftest.beam conftest.$ac_ext
-fi
-{ printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: $ac_cv_struct_sa_len" >&5
-printf "%s\n" "$ac_cv_struct_sa_len" >&6; }
-if test $ac_cv_struct_sa_len = yes; then
-  printf "%s\n" "#define HAVE_SOCKADDR_SA_LEN 1" >>confdefs.h
-
-fi
 
 report_use_address_sanitizer="no"
 { printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking if address sanitizer (asan) is wanted" >&5
@@ -15148,8 +14967,14 @@ cat confdefs.h - <<_ACEOF >conftest.$ac_ext
 
 /* Override any GCC internal prototype to avoid an error.
    Use char because int might match the return type of a GCC
-   builtin and then its argument prototype would still apply.  */
-char inflateEnd ();
+   builtin and then its argument prototype would still apply.
+   The 'extern "C"' is for builds by C++ compilers;
+   although this is not generally supported in C code supporting it here
+   has little cost and some practical benefit (sr 110532).  */
+#ifdef __cplusplus
+extern "C"
+#endif
+char inflateEnd (void);
 int
 main (void)
 {
